name: Daily Report

on:
  workflow_dispatch:
  schedule:
    - cron: "37 4 * * *"

jobs:
  dailyreport:
    runs-on: ubuntu-latest
    env:
      HOYMILES_PLANT_ID: ${{ vars.HOYMILES_PLANT_ID }}
      HOYMILES_USERNAME: ${{ secrets.HOYMILES_USERNAME }}
      HOYMILES_PASSWORD: ${{ secrets.HOYMILES_PASSWORD }}
      GOOGLE_SPREADSHEET_ID: ${{ vars.GOOGLE_SPREADSHEET_ID }}
      GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
      GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
      CONSO_API_TOKEN: ${{ secrets.CONSO_API_TOKEN }}

    steps:
      - uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: "npm"
      - run: npm ci
      - run: npm run fill-yesterday-report
